services:
  mongo_asiati:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  rabbitmq_asiati:
    image: rabbitmq
    ports:
      - "5672:5672"
    restart: always

  auth_asiati:
    build: ./auth
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      APP_ENV: "develop"
      MONGO_ATLAS_URL: ""
      DB_URL: "mongodb://mongo_asiati:27017/ecommerce_auth"
      REDIS_URL: "redis://rabbitmq_asiati"
      RABBITMQ_URL: "amqp://rabbitmq_asiati"
      BROKER_CHANNEL: "auth"
      MAX_QUEUE_MESSAGES: "1000"
      MAX_QUEUE_BYTES: "10485760"  # 10 MB
      MESSAGE_TTL: "60000"  # 1 minuto en milisegundos
      QUEUE_EXPIRATION: "3600000"  # 1 hora en milisegundos
      DLX_EXCHANGE: "dead-letter-exchange"
      DLX_ROUTING_KEY: "dead-letter-routing-key"
      JWT_SECRET: "ecommerce-ma-2024**-*/**/*/12355|324151512341"
    depends_on:
      - mongo_asiati
      - rabbitmq_asiati
    restart: always

  gateway_asiati:
    build: ./gateway
    ports:
      - "3080:3080"
    environment:
      PORT: "3080"
      APP_ENV: "develop"
      AUTH_URL: "http://auth_asiati:3000"
    depends_on:
      - auth_asiati
    restart: always

  notification_asiati:
    build: ./notifications
    environment:
      APP_ENV: "develop"
      BROKER_CHANNEL: "notifications"
      REDIS_URL: "redis://rabbitmq_asiati"
      RABITMQ_URL: "amqp://rabbitmq_asiati"
      EMAIL_USER: "maalhequi95@gmail.com"
      EMAIL_PASSWORD: "bteykyzvlxbqpwob"
      EMAIL_PROVIDER: "gmail"
      URL_CONFIRMATION: "http://gateway_asiati:3080"
    depends_on:
      - gateway_asiati
      - rabbitmq_asiati
    restart: always

volumes:
  mongo-data:
